# Generated by Django 3.1.8 on 2021-07-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime_Creator_App', '0002_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='C://Users/augus/Videos/UploadedVideos/'),
        ),
    ]
