# Generated by Django 3.1.8 on 2021-07-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime_Creator_App', '0003_auto_20210701_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='UploadedVideos/'),
        ),
    ]
