# Generated by Django 3.1.8 on 2021-07-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime_Creator_App', '0005_auto_20210701_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
