# Generated by Django 3.1.8 on 2021-07-04 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Anime_Creator_App', '0006_auto_20210703_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='creator',
        ),
        migrations.AddField(
            model_name='friends',
            name='friend',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
